<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_InRange" Id="{49259daf-98ab-4b7a-8dd3-2d45bf56c0dc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_InRange
VAR_INPUT
	i_fValue : LREAL;
	i_fRange : LREAL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
	nCntAuto : UINT;
	nCntManual : UINT;
	nCntMaintenance : UINT;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
SUPER^.m_Main();]]></ST>
    </Implementation>
    <LineIds Name="FB_InRange">
      <LineId Id="10" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>