<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_MovAvg" Id="{94161948-1aa6-4a27-a829-3f9dbd183760}" SpecialFunc="None">
    <Declaration><![CDATA[///This function calculates the moving avarage
// Based on the fuction below. 
// avg(n) = ( avg(n-1) * (n-1) + value(n) ) / n
FUNCTION_BLOCK FB_MovAvg
VAR_INPUT
	i_rIn : LREAL;
	i_nSamples : UINT;
END_VAR
VAR_OUTPUT
	o_rOut : LREAL;
END_VAR
VAR
	s_nSampleCounter : UINT;
	s_rVar : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
//o_rOut := 
]]></ST>
    </Implementation>
    <LineIds Name="FB_MovAvg">
      <LineId Id="22" Count="1" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>