<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_MovAvg" Id="{94161948-1aa6-4a27-a829-3f9dbd183760}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_MovAvg
VAR_INPUT
	i_rIn : LREAL;
	i_nSamples : UINT;
END_VAR
VAR_OUTPUT
	o_rOut : LREAL;
END_VAR
VAR
	s_nSampleCounter : UINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_MovAvg">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>