<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="HAL" Id="{3a9bd6e1-4674-4645-a5d3-1835b5ad1e40}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK HAL
]]></Declaration>
    <Implementation>
      <ST><![CDATA[							  
//--{attribute 'TcLinkTo' := 'TIID^Master (EtherCAT)^Term 1 (EK1200)^Term 7 (EL1008)^Channel 1^Input'}
//--     bVarIn2    AT%I*  : BOOL;  // linked via attribute 
	
// kan ook worden gebruikt om te verwijzen naar een andere PLC.
// Dit zou met name handig kunnen zijn wanneer er geschakel moet worden tussen Device Hardware en het simulatie projedt.
// Dan worden de linkings automatische gegenereerd, en hoeft dit dus niet meer handmatig te worden gedaan. |Veel tijd winst en kan op minder  fouiten.]]></ST>
    </Implementation>
    <LineIds Name="HAL">
      <LineId Id="10" Count="1" />
      <LineId Id="14" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="16" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>