<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Interlock" Id="{0f8e4d62-4669-4071-bb6b-34004672bcd7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Interlock
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Interlock">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>