<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="EM_AirTreatment" Id="{81e48a97-313d-405f-b257-49532a716bbe}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EM_AirTreatment EXTENDS EM_Base IMPLEMENTS I_EM_AirTreatment
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="m_Equalize" Id="{3dbf5f0e-de32-4d1f-a1ee-f80454ebc838}">
      <Declaration><![CDATA[METHOD PUBLIC m_Equalize : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="m_Flush" Id="{91abc485-ede4-4dc8-9260-f53c4f914a84}">
      <Declaration><![CDATA[METHOD PUBLIC m_Flush : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="m_Pressurize" Id="{7248c420-f75f-49e3-bdd0-b32fa28f9dd2}">
      <Declaration><![CDATA[METHOD PUBLIC m_Pressurize : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="p_bStaEqualizingDone" Id="{70485294-9ae5-46f7-b455-a30567b2984d}">
      <Declaration><![CDATA[PROPERTY PUBLIC p_bStaEqualizingDone : BOOL]]></Declaration>
      <Get Name="Get" Id="{512491e2-2c43-4c65-af17-560f948bfa0e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="p_bStaFlushingDone" Id="{e8505bce-20c5-4e11-a93c-d9c8bb05b3bb}">
      <Declaration><![CDATA[PROPERTY PUBLIC p_bStaFlushingDone : BOOL]]></Declaration>
      <Get Name="Get" Id="{56be4fba-47da-4dfb-819b-1e2798cd877e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="p_bStaPressurizingOK" Id="{7ff7c161-f01c-480d-8d30-a3ec8426337a}">
      <Declaration><![CDATA[PROPERTY PUBLIC p_bStaPressurizingOK : BOOL]]></Declaration>
      <Get Name="Get" Id="{a6f3a68e-e97d-4c33-8765-cf3f9408337e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="EM_AirTreatment">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="EM_AirTreatment.m_Equalize">
      <LineId Id="3" Count="0" />
    </LineIds>
    <LineIds Name="EM_AirTreatment.m_Flush">
      <LineId Id="3" Count="0" />
    </LineIds>
    <LineIds Name="EM_AirTreatment.m_Pressurize">
      <LineId Id="3" Count="0" />
    </LineIds>
    <LineIds Name="EM_AirTreatment.p_bStaEqualizingDone.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="EM_AirTreatment.p_bStaFlushingDone.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="EM_AirTreatment.p_bStaPressurizingOK.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>